### ISSUE TITLE
acr purge might have bug in date time calculation

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/acr-cli#66]
"-ago" doesn't seem to work as expected.
 
There're 2 images in the registry - one 35 days old and the other 36 days old (relative to 3/10). The test is like follow:
 
-ago36d -> didn't purge any images (expected to purge the 36 day old one)
-ago35d -> purged both
 
Images have the same name. Syntax was:

PURGE_CMD="acr purge --filter 'oneidentity/danedemoproject-supervisor:.*'  --ago 36d --dry-run"
az acr run   --cmd "$PURGE_CMD"   --registry starlingdev   /dev/null

**Comment by Wwwsylvia** [comment]
This is by design.

The purge results depend on the exact purge execution time. 
For the `--ago` argument,  `1d` = `1d0h0m0s`, counts (1* 24 * 60 * 60)s.

In this case, the customer has two tags:

> oneidentity/danedemoproject-supervisor:1.0.0:  2/3/2020, 5:41 PM MST
> oneidentity/danedemoproject-supervisor:1.0.1:  2/4/2020, 9:25 AM MST

Purge Time   |  Duration  | Duration
-- | -- | --
| Tag Creation Time | 2/3/2020, 5:41 PM MST | 2/4/2020, 9:25 AM MST
3/10/2020,   9:25 AM MST | 35 days, 15   hours, 44 minutes | 35 days, 0   hours, 0 minutes
3/10/2020,   5:41 PM MST | 36 days, 0 hours, 0   minutes | 35 days, 8 hours, 16   minutes
3/10/2020,   9:25 PM  MST | 36 days, 3 hours, 44   mintues | 35 days, 12 hours, 0   minutes


The customer purged BEFORE 3/10/2020, 5:41 PM MST, so `--ago 36d` purged no one,  `--ago 35d12h` purged tag 1.0.0 (2/3 one), `--ago 35d` purged both, which was as expected.
